<a href="https://colab.research.google.com/github/MorganDiaz2513892022/elt-data-pipeline-2513892022/blob/main/Notebooks/G_actividad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Morgan Alejandro Diaz Garcia 25-1389-2022

raw - G_Actividad

https://raw.githubusercontent.com/MorganDiaz2513892022/elt-data-pipeline-2513892022/refs/heads/main/data/G_actividad.csv

In [2]:
#importacion de pandas
import pandas as pd

In [5]:
url_G_Actividad = "https://raw.githubusercontent.com/MorganDiaz2513892022/elt-data-pipeline-2513892022/refs/heads/main/data/G_actividad.csv"

In [6]:
actividad = pd.read_csv(url_G_Actividad)

In [7]:
actividad.head()

  id_actividad id_usuario             accion      fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1      ACT9001      US512      cambio clave   2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta  2024-08-08 05:00:00  inventario

In [8]:
#Limpieza de data
def limpiar_dataframe(df):
    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)

    df = df.drop_duplicates()

    return df

In [9]:
actividad = limpiar_dataframe(actividad)

In [10]:
#tranformaciones
# fechas (si existe alguna)
if 'fecha' in actividad.columns:
    actividad['fecha'] = pd.to_datetime(actividad['fecha'], errors='coerce')

# números (ejemplo)
for col in actividad.select_dtypes(include='object').columns:
    if actividad[col].str.contains(",", na=False).any():
        actividad[col] = actividad[col].str.replace(",", ".")

In [12]:
#comprobacion
print(actividad.columns)

Index(['id_actividad', 'id_usuario', 'accion', 'fecha_actividad', 'modulo'], dtype='object')

In [13]:
actividad['fecha_actividad'] = pd.to_datetime(
    actividad['fecha_actividad'],
    errors='coerce'
)

In [16]:
#CURATED
curated = actividad[
    (actividad['id_actividad'].notna()) &
    (actividad['id_usuario'].notna()) &
    (actividad['accion'].notna()) &
    (actividad['fecha_actividad'].notna())
]

In [17]:
#REJECTS
rejects = actividad[~actividad.index.isin(curated.index)]

In [18]:
#verificacion
print("Curated:", curated.shape)
print("Rejects:", rejects.shape)

Curated: (224, 5)
Rejects: (16, 5)

In [20]:
#exportacion de archivos
curated.to_csv("actividad_curated.csv", index=False)
rejects.to_csv("actividad_rejects.csv", index=False)

In [22]:
#instalacion de librerias
!pip install sqlalchemy psycopg2-binary

#creacion de la conexion:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://etl_morgan:SZQ0Fw1oF4p5FEIzUmj4csiNVug5vFXz@dpg-d6viecs50q8c739ln0r0-a.oregon-postgres.render.com/etl_data_pipeline_2513892022"
)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 93.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [23]:
#comprobacion de conexion
import pandas as pd

pd.read_sql("SELECT 1;", engine)

   ?column?
0         1

In [25]:
#subir datos
curated.to_sql("actividad_curated", engine, if_exists="replace", index=False)
rejects.to_sql("actividad_rejects", engine, if_exists="replace", index=False)

16

In [26]:
#conteo de registros
pd.read_sql("SELECT COUNT(*) FROM actividad_curated;", engine)
pd.read_sql("SELECT COUNT(*) FROM actividad_rejects;", engine)

   count
0     16

In [27]:
#datos
pd.read_sql("SELECT * FROM actividad_curated LIMIT 5;", engine)

  id_actividad id_usuario             accion     fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido 2024-05-20 07:00:00   seguridad
1      ACT9001      US512       cambio clave 2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout 2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta 2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta 2024-08-08 05:00:00  inventario

In [28]:
#comprobacion de calidad
pd.read_sql("""
SELECT
    COUNT(*) AS total,
    COUNT(fecha_actividad) AS fechas_validas
FROM actividad_curated;
""", engine)

   total  fechas_validas
0    224             224

In [29]:
#CONSULTA
pd.read_sql("""
SELECT modulo, COUNT(*) AS total
FROM actividad_curated
GROUP BY modulo
ORDER BY total DESC;
""", engine)

       modulo  total
0  inventario     57
1   seguridad     54
2    reportes     43
3    usuarios     38
4      ventas     32

In [31]:
#actividad por usuario
pd.read_sql("""
SELECT id_usuario, COUNT(*) AS total
FROM actividad_curated
GROUP BY id_usuario
ORDER BY total DESC
LIMIT 10;
""", engine)

  id_usuario  total
0        nan      7
1      US440      5
2      US458      4
3      US472      4
4      US451      4
5      US418      4
6      US435      4
7      US476      4
8      US437      4
9      US444      4

In [32]:
#actividad por fecha
pd.read_sql("""
SELECT fecha_actividad, COUNT(*) AS total
FROM actividad_curated
GROUP BY fecha_actividad
ORDER BY fecha_actividad;
""", engine)

        fecha_actividad  total
0   2024-01-02 20:00:00      1
1   2024-01-03 05:00:00      1
2   2024-01-03 12:00:00      1
3   2024-01-03 18:00:00      1
4   2024-01-04 08:00:00      1
..                  ...    ...
215 2024-12-04 08:00:00      1
216 2024-12-04 21:00:00      1
217 2024-12-05 07:00:00      1
218 2024-12-05 13:00:00      1
219 2024-12-06 12:00:00      2

[220 rows x 2 columns]

In [38]:
#comprobacion de tablas
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
""", engine)

          table_name
0  actividad_curated
1  actividad_rejects

In [40]:
#subir clientes
import pandas as pd

url_clientes = "https://raw.githubusercontent.com/MorganDiaz2513892022/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

clientes = pd.read_csv(url_clientes)

In [41]:
#verificacion
print(clientes.head())

   id_cliente                 nombre                             email  \
0           1      José Chávez Pérez      jose.chavez.perez1@gmail.com
1           2    Daniela Rojas Ortiz    daniela.rojas.ortiz2@seguro.sv
2           3    Ricardo Cruz Flores  ricardo.cruz.flores3@example.com
3           4      María Pérez Pérez     maria.perez.perez4@correo.com
4           5  Fernanda Chávez Rojas  fernanda.chavez.rojas5@seguro.sv

      genero fecha_nacimiento          ciudad segmento
0     Hombre       2011/11/24       SanMiguel      NaN
1        NaN         01-02-80        Sta. Ana      NaN
2  Masculino         06-18-79       S. Miguel      NaN
3  Masculino       1960-09-29      LaLibertad  REGULAR
4        NaN       1945/08/02   San Salvador      Pyme

In [42]:
#definicion de funcion
def limpiar_dataframe(df):
    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)

    df = df.drop_duplicates()

    return df

In [43]:
#ultima limpieza
clientes = limpiar_dataframe(clientes)

clientes['fecha_nacimiento'] = pd.to_datetime(
    clientes['fecha_nacimiento'],
    errors='coerce',
    dayfirst=True
)

clientes['fecha_nacimiento'] = clientes['fecha_nacimiento'].dt.date

/tmp/ipykernel_291/3349952835.py:4: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  clientes['fecha_nacimiento'] = pd.to_datetime(

In [44]:
#subir a postgre
clientes.to_sql("clientes", engine, if_exists="replace", index=False)

30

In [48]:
actividad['id_usuario'] = pd.to_numeric(
    actividad['id_usuario'], errors='coerce'
)

In [49]:
#volver a subir
actividad.to_sql("actividad_curated", engine, if_exists="replace", index=False)

240

In [50]:
#verificacion
pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'actividad_curated';
""", engine)

       column_name                    data_type
0       id_usuario             double precision
1  fecha_actividad  timestamp without time zone
2     id_actividad                         text
3           accion                         text
4           modulo                         text